### ISSUE TITLE
ObjectTransport is looking for NewtonSoft ver 11

### ISSUE THREAD

**Issue by Skyhikeeper** [RhynoVDS/ObjectTransport#10]
Hi 
ObjectTransport is looking for NewtonSoft version 11, I have version 11.2 installed but ObjectTransport still fails.

Terence

**Comment by Skyhikeeper** [comment]
Message on the trycatch
Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

**Comment by Skyhikeeper** [comment]
Found the problem, NewtonSoft is a dependency but you don't include it in the references.

**Comment by RhynoVDS** [comment]
Hi Terence, Is this issue still occurring? Builds are passing fine.
