### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Opligitory** [RhynoVDS/ObjectTransport#3]
Hello again! i was wondering of it would be possible to make the ObjectTransport class not automatically connect to the passed IP and Port and instead be able to initiate a connection through a method it allow you to open a close the connection more then once?

**Comment by RhynoVDS** [comment]
Hi Opligitory,

Thanks for raising this feature request. I have been thinking the same thing and will likely have a look into this in the next few weeks. 
I've been thinking of something like:

var objectTransport =  ObjectTransport.Factory.CreateTCPClient().UseJSONserialization().Build();
.....
objectTransport.Connect("128.0.0.1",123);

Let me know your thoughts of what you would like it to look like.

**Comment by Opligitory** [comment]
Hey sorry for taking so long to get back with you about this idea, but i like idea of doing something like
```csharp
var objectTransport = ObjectTransport.Factory.CreateTCPClient().UseJSONserialization().Build();
objectTransport.Connect("128.0.0.1",123);
```
the only other suggesting i would have with this would be for 

```csharp 
objectTransport.Connect()
``` 
to return a bool value indicating if the connection was established successfully

**Comment by RhynoVDS** [comment]
Hey Opligitory,
Thanks for the response. I've been working on this and have changed the function name from Connect to Start.  

```
var objectTransport = ObjectTransport.Factory.CreateTCPClient().UseJSONserialization().Build();
objectTransport.Start("128.0.0.1",123);
```

This way we can use this function generically to also start a Server network channel. It's nearly done just trying to get all the tests green.

**Comment by RhynoVDS** [comment]
Hi Opligitory,

I have just finished writing the new Start function with all tests green and it's now released. Let me know what you think about it and please close this ticket if it's all good.

Thanks,
Regards,
Rhyno
