### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by midiway** [RhynoVDS/ObjectTransport#7]
I need to build a C# app that is a server for SQL queries.
Essentially the server accepts a SQL query and returns the results.
So I need to build a message oriented TCP server.

So I stumbled upon your lib. You seem to be creating a very nice fluent API for TCP communication.
I am right? How complete is it?

**Comment by RhynoVDS** [comment]
Hi midiway,
Thanks for your question. I'm continually supporting this project. Currently it is possible to send and receive messages using the API.
I recommend playing around with the API and seeing if it meets your requirements.
The only thing that I will mention is that I have not implemented any encryption yet so you will need to implement that your self. But it is something I will be working on soon.

**Comment by midiway** [comment]
I don't need encryption.
What I would like is built-in compression.

**Comment by midiway** [comment]
take a look at GZipStream which is standard in C#

**Comment by RhynoVDS** [comment]
You could use the Protobuf serializer, there is an implementation that I've implemented already available on Nuget. If you want to use compression, you could set a string property of an object to a compressed  value and send it.
